'use strict';

// типы действий, приходящих по сокетам с клиентов
module.exports = {

	JOIN_ROOM: 'JOIN_ROOM',
	LEAVE_ROOM: 'LEAVE_ROOM',
	
	UPDATE_SECTIONS: 'UPDATE_SECTIONS',

	UPDATE_SECTION_BY_ID: 'UPDATE_SECTION_BY_ID',
	DELETE_SECTION_BY_ID: 'DELETE_SECTION_BY_ID',

	UPDATE_SUBSECTION_BY_ID: 'UPDATE_SUBSECTION_BY_ID',
	DELETE_SUBSECTION_BY_ID: 'DELETE_SUBSECTION_BY_ID',

	UPDATE_CHANNEL_BY_ID: 'UPDATE_CHANNEL_BY_ID',
	DELETE_CHANNEL_BY_ID: 'DELETE_CHANNEL_BY_ID',

	UPDATE_MESSAGE_BY_ID: 'UPDATE_MESSAGE_BY_ID',
	DELETE_MESSAGE_BY_ID: 'DELETE_MESSAGE_BY_ID',

	UPDATE_PRIVATE_CHANNEL_BY_ID: 'UPDATE_PRIVATE_CHANNEL_BY_ID',
	DELETE_PRIVATE_CHANNEL_BY_ID: 'DELETE_PRIVATE_CHANNEL_BY_ID',

	UPDATE_USER: 'UPDATE_USER',
};




